version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace:cached
    ports:
      - 8000:8000
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
      - .env
