version: '3'
services:
  jupyterlab:
    build: .
    container_name: jupyterlab-analysis
    working_dir: /analysys
    volumes:
      - ./:/analysys
    ports:
      - "8888:8888"
    command:
      jupyter-lab --ip 0.0.0.0 --allow-root -b localhost